### ISSUE TITLE
Consider using tempfile for autogenerated sketches

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#81] opened 2019-04-09 05:10 UTC
Library reference: https://docs.python.org/3.5/library/tempfile.html#module-tempfile This way the file is deleted automatically when the Python program terminates. We can persist it if required.

**Comment by taegyunkim** [comment] 2019-04-24 01:07
#95 the appveyor script actually caught this issue. We'd better use temp files for generated files.

**Comment by anirudhSK** [comment] 2019-04-24 01:40
I get why the appveyor script fails but how would using temp files help
with this issue?

**Comment by taegyunkim** [comment] 2019-04-24 02:00
I haven't read the details of the temp file in python documentation. However, my initial thinking was that after each test we would also want to clear temporary files before executing next one. I am not sure tempfile module automatically does that for each test?

**Comment by anirudhSK** [comment] 2019-04-24 03:10
I see. By default the tempfile module deletes files. So yes, it would have
caught this bug earlier.

We should probably just check in the file that's being read as part of this
test.

**Comment by taegyunkim** [comment] 2020-01-03 03:02
Duplicate of #188

**Closed as completed by taegyunkim** 2020-01-03 03:02 UTC
Labels: enhancement
