### ISSUE TITLE
pkt-fields argument doesn't work correctly

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#136] opened 2019-06-08 05:47 UTC
iterative_solver June_7_experiment/sampling/sampling_equivalent_3_canonicalizer_equivalent_0.sk example_alus/if_else_raw.stateful_alu stateless_alus/stateless_alu.j2 3 3 10 --pkt-fields 3

returns a syntax error.

To run this program, we need to clone https://github.com/chipmunk-project/chipmunk_experiments and run iterative_solver (assumed to be on the path) from the chipmunk_experiments repository.

**Comment by anirudhSK** [comment] 2019-06-08 06:22
This isn't a straightforward fix. Let's not support the pkt-fields argument for now.

**Comment by taegyunkim** [comment] 2019-06-08 13:58
I am not sure whether --pkt-fields flag is the cause of error. 
Even if I run modified command without --pkt-fields 3, it returns an error like following. With --pkt-fields 3,
it returns the same error. 

```
$> iterative_solver June_7_experiment/sampling/sampling_equivalent_3_canonicalizer_equivalent_0.sk example_alus/if_else_raw.stateful_alu stateless_alus/stateless_alu.j2 3 3 10
Traceback (most recent call last):
  File "/home/taegyunk/.pyenv/versions/3.5.4/envs/chipmunk/bin/iterative_solver", line 11, in <module>
    load_entry_point('chipc', 'console_scripts', 'iterative_solver')()
  File "/home/taegyunk/Workspace/chipmunk/chipc/iterative_solver.py", line 203, in run_main
    sys.exit(main(sys.argv))
  File "/home/taegyunk/Workspace/chipmunk/chipc/iterative_solver.py", line 152, in main
    sketch_name, args.parallel_sketch, args.pkt_fields)
  File "/home/taegyunk/Workspace/chipmunk/chipc/compiler.py", line 59, in __init__
    self.num_fields_in_prog, num_alus_per_stage))
AssertionError: Number of fields in program 6 is greater than number of alus per stage 3. Try increasing number of alus per stage.
```

**Comment by anirudhSK** [comment] 2019-06-08 14:47
That assertion needs to be fixed to support pkt-fields. But, even if it was fixed, there's more work required to support pkt-fields.

**Comment by taegyunkim** [comment] 2019-06-13 20:26
Need to handle cases where there are more packet fields than phv containers.

**Comment by taegyunkim** [comment] 2020-01-03 03:04
In a slightly different context, #194 implements --pkt-fields. Closing.

**Closed as completed by taegyunkim** 2020-01-03 03:04 UTC
Labels: enhancement
